### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by ttakkku** [aliyr/Nodejs-Developer-Roadmap#16]
![image](https://user-images.githubusercontent.com/42809517/77497477-be94f300-6e90-11ea-8346-b86357cd0b08.png)

**Comment by ttakkku** [comment]
![image](https://user-images.githubusercontent.com/42809517/77497549-ee43fb00-6e90-11ea-87fb-081f82e4134a.png)

**Comment by hpandelo** [comment]
Language: Portugês = pt-BR (or pt-PT in some cases)

**Comment by ttakkku** [comment]
okay
